const myFunc = () => {
	return new Promise((resolve, reject) => {
		 setTimeout (
			() => {
				reject('Meu erro fabricado aqui!!!');
			},
			2000
		);
	});
};
await myFunc();
